// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) updateOutput;
-(IBAction) countdownHasChanged;
-(IBAction) countdownHasFinished;
-(IBAction) applicationDidEnterBackground:(id) application;
-(IBAction) applicationDidBecomeActive:(id) application;

@end

@interface AppearanceController: UIViewController

@property IBOutlet UIView * previewView;
@property IBOutlet UIImageView * previewImageView;
@property IBOutlet UILabel * previewLabel;
@property IBOutlet UISlider * fontScaleSlider;

-(IBAction) viewDidLoad;
-(IBAction) done;
-(IBAction) chooseBackground;
-(IBAction) clearBackground;
-(IBAction) fontScaleChanged;
-(IBAction) updateAppearance;
-(IBAction) imagePickerControllerDidCancel:(id) picker;

@end

@interface CountdownController: UIViewController

@property IBOutlet UIView * previewView;
@property IBOutlet UIImageView * previewImageView;
@property IBOutlet UILabel * previewLabel;
@property IBOutlet UILabel * outputStatusLabel;
@property IBOutlet UILabel * lengthLabel;
@property IBOutlet UIView * countdownLengthView;
@property IBOutlet UITextField * minutesTextField;
@property IBOutlet UITextField * secondsTextField;
@property IBOutlet UIButton * startButton;
@property IBOutlet UIButton * stopButton;
@property IBOutlet UIButton * resetButton;

-(IBAction) viewDidLoad;
-(IBAction) preferredStatusBarStyle;
-(IBAction) supportedInterfaceOrientations;
-(IBAction) viewWillLayoutSubviews;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) updateCountdownLength;
-(IBAction) updateLengthLabel;
-(IBAction) start;
-(IBAction) stop;
-(IBAction) reset;
-(IBAction) plusOneMinute;
-(IBAction) editCountdownLength;
-(IBAction) finishCountdownLength;
-(IBAction) countdownHasFinished;

@end

@interface OutputController: UIViewController

@property IBOutlet UILabel * timeLabel;
@property IBOutlet UIImageView * backgroundImageView;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) updateAppearance;

@end

@interface Appearance: NSObject
-(IBAction) initialize;

@end

@interface CountdownTimer: NSObject
-(IBAction) initialize;
-(IBAction) setTime:(id) length;
-(IBAction) start;
-(IBAction) stop;
-(IBAction) reset;
-(IBAction) tick;
-(IBAction) addToRemaining:(id) amount;

@end

