// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation AppearanceController
@end

@implementation CountdownController
@end

@implementation OutputController
@end

@implementation Appearance
@end

@implementation CountdownTimer
@end

