// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <StoreKit/StoreKit.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) updateOutput;
-(IBAction) countdownHasChanged;
-(IBAction) countdownHasFinished;
-(IBAction) applicationDidEnterBackground:(id) application;
-(IBAction) applicationDidBecomeActive:(id) application;

@end

@interface AppearanceController: UIViewController

@property IBOutlet UIView * previewView;
@property IBOutlet UIImageView * previewImageView;
@property IBOutlet UILabel * previewLabel;
@property IBOutlet UIView * borderView;
@property IBOutlet UIView * settingsView;
@property IBOutlet UIView * fontView;
@property IBOutlet UISlider * fontScaleSlider;
@property IBOutlet UIButton * fontWeightButton;
@property IBOutlet UIView * backgroundView;
@property IBOutlet UISegmentedControl * fontBackgroundControl;
@property IBOutlet UIView * colorPickerBorder;

-(IBAction) viewDidLoad;
-(IBAction) viewDidLayoutSubviews;
-(IBAction) done;
-(IBAction) reset;
-(IBAction) chooseBackground;
-(IBAction) clearBackground;
-(IBAction) fontScaleChanged;
-(IBAction) toggleBoldFont;
-(IBAction) fontBackgroundToggle;
-(IBAction) updateAppearance;
-(IBAction) imagePickerControllerDidCancel:(id) picker;

@end

@interface CountdownController: UIViewController

@property IBOutlet UIView * previewView;
@property IBOutlet UIImageView * previewImageView;
@property IBOutlet UILabel * previewLabel;
@property IBOutlet UILabel * outputStatusLabel;
@property IBOutlet UILabel * lengthLabel;
@property IBOutlet UIView * countdownLengthView;
@property IBOutlet UITextField * minutesTextField;
@property IBOutlet UITextField * secondsTextField;
@property IBOutlet UIButton * startButton;
@property IBOutlet UIButton * stopButton;
@property IBOutlet UIButton * resetButton;

-(IBAction) viewDidLoad;
-(IBAction) preferredStatusBarStyle;
-(IBAction) supportedInterfaceOrientations;
-(IBAction) viewWillLayoutSubviews;
-(IBAction) viewDidLayoutSubviews;
-(IBAction) updateAppearance;
-(IBAction) updateCountdownLength;
-(IBAction) updateLengthLabel;
-(IBAction) start;
-(IBAction) stop;
-(IBAction) reset;
-(IBAction) plusOneMinute;
-(IBAction) editCountdownLength;
-(IBAction) finishCountdownLength;
-(IBAction) countdownHasFinished;

@end

@interface IAPController: UIViewController

@property IBOutlet UILabel * titleLabel;
@property IBOutlet UILabel * descriptionLabel;
@property IBOutlet UILabel * priceLabel;

-(IBAction) viewDidLoad;
-(IBAction) done;
-(IBAction) purchase;
-(IBAction) restore;

@end

@interface OutputController: UIViewController

@property IBOutlet UILabel * timeLabel;
@property IBOutlet UIImageView * backgroundImageView;

-(IBAction) viewDidLoad;
-(IBAction) viewDidLayoutSubviews;
-(IBAction) updateAppearance;

@end

@interface Appearance: NSObject
-(IBAction) initialize;
-(IBAction) save;
-(IBAction) reset;
-(IBAction) fontName;

@end

@interface CountdownTimer: NSObject
-(IBAction) initialize;
-(IBAction) setTime:(id) length;
-(IBAction) start;
-(IBAction) stop;
-(IBAction) reset;
-(IBAction) tick;
-(IBAction) addToRemaining:(id) amount;

@end

